// Problem 2
// Even Fibonacci numbers 
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'use strict';

function evenFibSum(num) {
    let result = [];
    let a = 1, b = 2;
    while( a < num || b < num ) {
        if (a % 2 === 0) {
            result.push(a);
        } else if (b % 2 === 0) {
            result.push(b);
        };
        
        a = a + b; 
        b = b + a; 
    
    };

    console.log(result.reduce((a,b)=>a+b))
}

console.time('\nResult generated in');
evenFibSum(4000000)
console.timeEnd('\nResult generated in');


// result is 4613732