# Problem 2
# Even Fibonacci numbers 
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
import timeit

def even_fib_sum(num):
    result = []
    a, b = 1, 2
    while a < num:
        if a % 2 == 0:
            result.append(a)
        a, b = b, a + b
    return (sum(result))





# result is 4613732

def wrapper(func, *args, **kwargs):
    def wrapped():
        return func(*args, **kwargs)
    return wrapped

argument = 4000000
wrapped = wrapper(even_fib_sum, argument)

elapsed_time = timeit.timeit(wrapped, number=1000)
print(even_fib_sum(argument))
print('\nResult generated in {} ms.'.format(round(elapsed_time,4)))